name: Checks
on: [pull_request]

concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs of this workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

env:
  # reduces noise from npm post-install scripts
  DISABLE_OPENCOLLECTIVE: true
  OPEN_SOURCE_CONTRIBUTOR: true

jobs:
  commitlint:
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: './package.json'
  docs:
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: install
        run: npm ci
      - name: regenerate docs
        run: npm run tools:generate-configs-list
      - name: report regenerated docs
        run: |
          git diff --name-only \
            | xargs -I '{}' bash -c \
              'echo "::error file={}::This needs to be regenerated by running \`tools:generate-configs-list\`" && false'
  lint:
    permissions:
      contents: read # to fetch code (actions/checkout)
    # prettier-ignore
    name: Lint on ${{ matrix.os }} with eslint v${{ matrix.eslint }}, using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        eslint: [7, 8]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm install eslint@${{ matrix.eslint }} --no-fund
      - run: npm run lint
  test:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm run test
  typecheck:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Typecheck on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm run typecheck
